### ISSUE TITLE
Unable to push to organization

### ISSUE THREAD

**Issue by naveensrinivasan** [app-registry/helm-plugin#8]
I am trying to use `helm registry push --namespace upskill quay.io` where `upskill` is an organization within quay.io.

```  bash
usage: cnr [-h]
           {show,inspect,logout,plugins,helm,pull,list,delete-package,version,push,login,config,channel}
           ...
cnr: error: 501 Server Error: NOT IMPLEMENTED for url: https://quay.io/cnr/api/v1/packages/upskill/nginx?force=false
Error: plugin "registry" exited with error
```
It is failing. How can I push to an organization?

**Comment by ant31** [comment]
cc @jzelinskie / @josephschorr

**Comment by ant31** [comment]
@naveensrinivasan Thanks for report, the returned error is wrong and it is going to be fixed

It is a conflict with a container-image repository, you can't have an application and image with the same name.

**Comment by naveensrinivasan** [comment]
OK, Thanks. How do I have containers repo with name `nginx` and a helm chart with the same name? 

Isn't that what anyone would expect?

**Comment by josephschorr** [comment]
@naveensrinivasan: Simple answer is, you don't. Typically, you'd have the image be named something like `nginx-image` or have the app named `nginx-app`. The reasoning behind this decision is that *most* applications (not all) will consist of not a single container image but many; if we were to allow both applications and image repositories to share the same name, it could get confusing for users who aren't the author of the app+image(s), not to mention make it harder for us to have nice URLs such as `quay.io/somenamespace/somename`. We therefore currently force you to use a different name. If we find that this restriction turns out to be too annoying, we might revisit it in the future.

To make this more clear, we've submitted a patch internally to change the HTTP status code, and add an error message detailing why this is the case.

Sorry for the confusion!

**Comment by naveensrinivasan** [comment]
@josephschorr  Thanks for the detailed response. I understand.
